spring:
  application:
    name: chirpchat
  config:
    import: optional:configserver:http://localhost:8070/
  profiles:
    active: prod
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/chirp/protocol/openid-connect/certs

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: '*'

chirp:
  gateway:
    base-url: http://localhost:8071/chirp